### ISSUE TITLE
Renaming and Refactoring

### ISSUE THREAD

**Issue by blacksmithgu** [phil-opp/rust-bit-field#4] opened 2017-01-06 08:58 UTC
As with all renaming and refactoring, this is of course subjective, but there were a few things which I noticed could be cleaned up a little bit (as breaking changes, though, of course):

- BitField can be made much more generic and operate on signed-integral types and non-integral types (like slices and vectors of integral values). Doing so neccessitates simplifying the API of BitField a little bit to just have `length` and the bit operations, and then specializing the implementation for unsigned integers, signed integers, and slices/vectors seperately.

- Having a `length` field pollutes the namespace somewhat by not being sufficiently descriptive; maybe `bit_length`? `zero` and `one` also do so, but removing them and specializing the implementation as the above point suggests fixes that seperately.

- Similarly, `set_range` could be renamed to either `set_bits` or `set_bit_range` for clarity's sake.

- The set functions take the value by mutable reference; it would be nice to see (optional) methods for taking by value, which need only be implemented on the integral types and would allow things like

```rust
0u32.set_bit(1, true).set_bit(2, true)
```

- The use of a u8 for the index seems arbitrary; it works fine for the existing integral types, but the trait could be made more general by using `usize`.

Of course, most of this is nitpicking, but if any of it seems mildly appealing I would be more than happy to make any neccessary changes and create a PR.

**Comment by phil-opp** [comment] 2017-01-06 14:10
These are some great suggestions overall. Thanks a lot!

> Having a `length` field pollutes the namespace somewhat by not being sufficiently descriptive; maybe `bit_length`? […] Similarly, `set_range` could be renamed to either `set_bits` or `set_bit_range` for clarity's sake. […] 

Agreed!

> The set functions take the value by mutable reference; it would be nice to see (optional) methods for taking by value, which need only be implemented on the integral types and would allow things like […]

Hmm, I'm not sure about this one. The problem is that it's easy to accidentally drop a value this way:

```rust
let x = 0;
x.set_bit(1, true); // return value is ignored, x is still 0
```
As an alternative, the methods could return `&mut self`. This would allow optional chaining:

```rust
let mut x = 0;
x.set_bit(1, true).set_bit(2, true); // x is now 0b11
```
However, this approach has downsides, too. For example, consider the `update` method of the [`volatile::ReadWrite`](https://docs.rs/volatile/0.2.1/volatile/struct.ReadWrite.html#method.update) type, that updates a volatile `T` through a `FnOnce(&mut T)`. With chaining support, one would have to write `x.update(|v| { v.set_bit(1, true);})` instead of `x.update(|v| v.set_bit(1, true));`.

> BitField can be made much more generic and operate on signed-integral types and non-integral types (like slices and vectors of integral values). Doing so neccessitates simplifying the API of BitField a little bit to just have length and the bit operations, and then specializing the implementation for unsigned integers, signed integers, and slices/vectors seperately.

I deliberately left out signed integral types, since setting arbitrary bits can have side effects (e.g. setting the most significant bit flips the sign). But I assume that anybody who uses this crate knows such things. So I think I'm fine with adding implementations for signed integral types.

I'm not sure about non-integral types. Is it really a good idea to do things like `let mut x = [0u32; 8]; x.set_bit(179, true);`? IMO it's much cleaner to write `x[5].set_bit(19,true);`.

> The use of a u8 for the index seems arbitrary; it works fine for the existing integral types, but the trait could be made more general by using usize.

Not sure about this one… depends on whether we allow non-integral types…

**Comment by blacksmithgu** [comment] 2017-01-06 22:59
Points well taken! I see what you mean with the issues of taking by value, there doesn't seem to be much of a winning situation here, so the current one is probably best. My usage of this crate has always been like this:

```rust
let thing = ...;
thing.set_range(0..4, ...);
thing.set_range(4..8, ...);
```

anyway, so there's not too much ergonomics being lost here. The other option is to have a take-by-value set of functions like ".update_bit", but it's hard to name them where their usage is unambiguous, which makes that idea something of a non-starter.

As for the signed integral types, the sign bit is indeed a little tricky, but people have to interact with this trickery any time they do bitwise operations (`<<`, `>>`, `&`, `^`, etc) anyway, which is why I think it's okay.

And for non-integral types, I agree that having wierd types like &[u32] and doing bitwise operations on them seems a little arbitrary. How about a more limited approach, where we just support doing bitwise operations on &[u8] slices? This would allow for use cases like interacting with bit-vectors, or having nice abstractions over big memory-mapped registers in operating systems, and so on, without letting people just be silly.

**Comment by blacksmithgu** [comment] 2017-01-07 08:36
It is also feasible to add a simple macro, called "bit_field!" or something, which simply used the BitField underlying methods to generate a struct which had nice getters/setters and wrapped some simply underlying integer type like u32 or u64.

For example (syntax highly arbitrary),

```rust
bit_field! {
    PageEntry : u64 {
        present : bit 0,
        writable : bit 1,
        ...
    }
}
```

(For constructing a nice wrapper around a page table entry in x86 paging).

**Comment by phil-opp** [comment] 2017-01-10 12:28
> As for the signed integral types, the sign bit is indeed a little tricky, but people have to interact with this trickery any time they do bitwise operations (<<, >>, &, ^, etc) anyway, which is why I think it's okay.

Good point!

> How about a more limited approach, where we just support doing bitwise operations on &[u8] slices? This would allow for use cases like interacting with bit-vectors, or having nice abstractions over big memory-mapped registers in operating systems, and so on, without letting people just be silly.

Bit-vectors are indeed a good use case!

> It is also feasible to add a simple macro, called "bit_field!" or something, which simply used the BitField underlying methods to generate a struct which had nice getters/setters and wrapped some simply underlying integer type like u32 or u64.

I like the idea, but I'm not sure if it's possible (I'm no macro

**Comment by phil-opp** [comment] 2017-01-10 13:34
> All in all, if there are any of these you think are okay, I would be happy to send another pull request for you to look at!

That would be great! I really like your refactoring/renaming ideas overall.

**Comment by le-jzr** [comment] 2017-04-04 11:11
>I'm not sure about non-integral types. Is it really a good idea to do things like `let mut x = [0u32; 8]; x.set_bit(179, true);`? IMO it's much cleaner to write `x[5].set_bit(19,true);`.

Is it really? In such a contrived example with constant indices, it might seem that way, but consider something like e.g. a bitmap allocator:
```
fn allocate(&mut self, frame_index: usize) ->... {
    if self.get_bit(frame_index) {
        Err(...)
    } else {
        self.set_bit(frame_index, true);
        Ok(...)
    }
}
```
vs
```
fn allocate(&mut self, frame_index: usize) ->... {
    // Possibly needs explicit casts too, not sure.
    if self.map[frame_index / 8].get_bit(frame_index % 8) {
        Err(...)
    } else {
        self.map[frame_index / 8].set_bit(frame_index % 8, true);
        Ok(...)
    }
}
```

And you absolutely want to use `u64` elements in that bit vector, for search performance.
On the other hand, general arbitrary-length bitvectors might be a little out of scope of this library.
On the other other hand, I did a quick search for other existing bitvector crates and they all seem quite [overcomplicated](http://contain-rs.github.io/bit-vec/bit_vec/).
On the other other other hand, in order to be useful for e.g. bitmap allocators, it would need a bunch more methods, like searching for a span of consecutive zeros/ones.

My conclusion is that I totally want a bitvector implementation that's as simple as bit-field, but I'm not sure adding arbitrary new methods to this so far beautifully simple crate is advisable.

**Comment by kjetilkjeka** [comment] 2017-06-07 13:35
Here is one aspect of the slice as BitField discussion.

The ```x[5].set_bit(19, true)``` is probably cleaner in most cases, but consider the following scenario.

I'm currently working with a protcol on top of the CAN transport layer, it should atleast support CAN-frames (0-8 byte data) and CAN-FD (0-64 byte data).

Since data structures are packed tightly (not aligned at 8 bits) it would make perfect sense to get a slice for the data in the can frame and iterate per bit when parsing and serializing. This will require to keep a ```bit_pointer``` and when serializing/parsing a data structure of x bits i will increment it by x. Now consider which syntax is cleaner.

Alternative 1:
- find out how many bits that needs to be changed
- find out how many bytes those bits span
- handle change of first byte (since this might be only partially changed)
- handle middle bytes (since they are read from 1 byte if bit offset is 0 and 2 bytes if not)
- handle last byte (since this might be only partially changed)

Alternative 2:

    value.set_bits(bit_pointer..bit_pointer+field.bit_length(), field);


This is a clear use case for the [u8] as a bit field, and i really think this should be implemented regardless if the [BitField] implementation is made.

On the other side I don't see much reason not to do ```impl<T: BitField> [T]``` except those mentioned in #8. 

I believe the behaviour is intuitive, and if you want to do something crazy like accessing [i16] as a bitfield you probably have a really good reason to do so. And if you really wish to do something crazy there are much worse alternatives.

**Comment by phil-opp** [comment] 2017-06-08 10:50
I agree that an `BitField` implementation for `[x8]`, `[u64]`, and even `[i16]` would useful in some cases. However, I'm not sure if reusing the `BitField` trait for this is a good idea. For example, what should the return type of `get_bits` be? `usize`? `[bool]`?

Perhaps it's better to create a second `BitVector` trait that provides `get_bits_u8`, `get_bits_usize`, etc. methods (and maybe additional methods as @le-jzr proposed). This would keep the `BitField` trait simple and would prevent accidental bit vector use (e.g. the user wanted to write `x[5].get_bit(5)` but accidentally wrote `x.get_bit(5)`, with separate traits this only works if both traits are imported).

**Comment by phil-opp** [comment] 2017-11-15 10:15
Most of the suggestions are implemented now, so I'm going to close this issue. If you feel like anything was unaddressed here, please open a new one.

**Closed by phil-opp** 2017-11-15 10:15 UTC
